project: NBME-ScoreClinicalPatientNotes
_wandb_kernel: MPEG
apex: true
batch_scheduler: true
batch_size: 16
betas: 
    - 0.9
    - 0.999
ckpt_name : mpeg_deberta_large
decoder_lr: 2.5e-5
device: cuda
debug: false
encoder_lr: 2.5e-5
epochs: 5
eps: 1e-6
gradient_accumulation_steps: 2
max_len: 512
max_grad_norm: 1000
min_lr: 8e-6
model: microsoft/deberta-v3-large
n_folds: 5
num_cycles: 0.5
num_warmup_steps: 0
num_workers: 4
optim: adamw
output_dir: ../output/
print_freq: 100
scheduler: cosine
seed: 42
weight_decay: 0.01
description: empty
adv_lr: 1
adv_eps: 0.0001
adv_start_epoch: 3
